services:
  photobook:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__SqlConnection=Server=photobook.db;Database=photobook_db;User Id=sa;Password=Taggia42!
      - ConnectionStrings__AzureStorageConnection=DefaultEndpointsProtocol=https;AccountName=satelemetrydom;AccountKey=kLPYHtaddlQzzmor/LCWiXWSMJ/pxq1tTHEx8v3ofJqwwXp0qZmCpp09KvV2lpW0fHVIkIAKyzFjot42l4xr7A==;EndpointSuffix=core.windows.net
      - AppSettings__ContainerName=attachments
      - AppSettings__CognitiveServicesKey=cbf85f9b5f5546c298ee5c618b55e5f1
      - AppSettings__CognitiveServicesEndpoint=https://cogntelemetrydom.cognitiveservices.azure.com/
      - AppSettings__OtelEndpoint=http://otel:4317
      #- ConnectionStrings__AzureStorageConnection=${STORAGEACCOUNTCONNECTION}
      #- AppSettings__ContainerName=attachments
      #- AppSettings__CognitiveServicesKey=${COGNITIVESERVICESKEY}
      #- AppSettings__CognitiveServicesEndpoint=${COGNITIVESERVICESENDPOINT}
      #- AppSettings__OtelEndpoint=${OTELENDPOINT}
    ports:
      - "8081:80"
      - "44328:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  db:
    ports:
      - "6999:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Taggia42!"
